services:
  bdo-api:
    image: man90/bdo-rest-api:latest
    container_name: bdo-api
    restart: always
    command: ["-redis", "redis://redis:6379/0"]
    depends_on:
      - redis
    networks:
      - clarity-internal

  redis:
    image: redis:7-alpine
    container_name: clarity-redis
    restart: always
    volumes:
      - ./redis-data:/data
    networks:
      - clarity-internal

  clarity-backend:
    image: node:20-alpine
    container_name: clarity-backend
    restart: always
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./data:/data
    command: sh -c "npm install && node server.js"
    environment:
      - DB_PATH=/data/clarity.db
      - BDO_API_URL=http://bdo-api:8001
      - GUILD_NAME=clarity
      - REGION=EU
      - ADMIN_TOKEN=54f68e6e0a6adada4a5d74e53be9a66cfa9b49e5eccf608e52275dd8a5715ed5
      - DISCORD_WEBHOOK=https://discord.com/api/webhooks/1507321177121624084/0AyDVHQ9ak-GBBbwK-RBVg0yMzpr6T-ITSgb30sADafIE9m0KqK5x5PCt1TXarCHja_4
    depends_on:
      - bdo-api
    networks:
      - proxy-net
      - clarity-internal

networks:
  proxy-net:
    external: true
  clarity-internal:
    driver: bridge
